- hosts: all
  become_method: sudo

  tasks:
    - name: Update APT Cache
      apt: update_cache=yes
      become: yes

    - name: Install build packages
      apt:
          state: present
          name:
              - miniupnpc
      become: yes